<!-- application/views/scripts/index/index.phtml -->
<main class="main column full">
	<section class="base-block">
		<div class="slideshow">
			<img src="images/slideshow/image_1.png" width="961" height="305" class="slide">
		</div>
		<div class="slides-pager">
			<span class="pager-button"></span>
			<span class="pager-button active"></span>
			<span class="pager-button"></span>
			<span class="pager-button"></span>
			<span class="pager-button"></span>
		</div>
	</section>

	<section class="base-block new-releases">
		<h2 class="big-headline" title="New releases">New Releases</h2>
		<div class="tab-bar">
			<a href="#" class="tab active" title="Women">Women</a>
			<a href="#" class="tab" title="Men">Men</a>
			<a href="#" class="tab" title="Kids">Kids</a>
		</div>

		<div class="container">
			<div class="story first">
				<img src="images/block_1.png" class="photo" width="293" height="296">
				<div class="byline">
					<p>Lorem ipsum dolor</p>
				</div>
			</div>
			<div class="story second">
				<img src="images/block_2.png" class="photo" width="293" height="296">
				<div class="byline">
					<p>Lorem ipsum dolor</p>
				</div>
			</div>
			<div class="story third">
				<img src="images/block_3.png" class="photo" width="293" height="296">
				<div class="byline">
					<p>Lorem ipsum dolor</p>
				</div>
			</div>
		</div>
	</section>

	<section class="base-block main-content text-column clearfix">
		<h2 class="big-headline" title="Lorem Ipsum Dolor">Lorem Ipsum Dolor</h2>
		<div class="story grid-column full">
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus at libero sed diam ullamcorper ornare. Morbi adipiscing quam quis quam facilisis sed faucibus urna vehicula. Vestibulum malesuada justo nec tortor commodo bibendum. Nulla at urna sed est cursus consectetur ut ut lacus. Nunc ornare tempus quam, ullamcorper tempor ante sagittis sit amet. Sed nisl velit, commodo ac interdum quis, luctus sed lorem. In hac habitasse platea dictumst.</p>
			<p>Mobi ipsum dolor sit amet, consectetur adipiscing elit. ornare. Vestibulum malesuada justo nec tortor commodo bibendum. </p>
			<p>Vivamus at libero sed diam ullamcorper ornare. Morbi adipiscing quam quis quam facilisis sed faucibus urna vehicula. Vestibulum malesuada justo nec tortor commodo bibendum. Sed nisl velit, commodo ac interdum quis, luctus sed lorem. In hac habitasse platea dictumst.</p>
		</div>
	</section>
</main>