<!-- application/views/scripts/footer.phtml-->
<footer class="footer grid-column full clearfix">
	<div class="container base-block clearfix">
		<div class="column grid-column third">
			<h3 class="big-headline grid-column third" title="Footer">Footer</h3>
			<a href="#" class="social facebook-icon" title="Facebook">Facebook</a>
			<a href="#" class="social twitter-icon" title="Twitter">Twitter</a>
		</div>
		<div class="column grid-column third">
			<h3 class="big-headline" title="Contact us">Contact</h3>
			<ul class="contact-info">
				<li>Company name</li>
				<li>730 Fifth Avenue 9th Floor</li>
				<li>New York, NY 10019</li>
				<li>USA</li>
			</ul>
		</div>
		<div class="column grid-column subscribe third">
			<h3 class="big-headline" title="Subscribe to newsletter">Subscribe</h3>
			<form class="subscribe-form inset-field" id="newsletter">
				<input type="email" class="text-field" id="email" name="email" value="Enter your email address...">
				<input type="submit" class="btn subscribe" id="subscribe-btn" value="Submit" title="Subscribe to newsletter">
			</form>
			<p class="alert newsletter"></p>
		</div>
	</div>
	<div class="copyright horisontal-separator-before">
		<div class="base-block">
			<p title="Copyright 2012 - All rights reserved">&copy; Copyright 2012, All Rights Reserved</p>
		</div>
	</div>
</footer>
