<!-- application/views/scripts/header.phtml-->
<header class="header-container grid-column full">
	<div class="header-block top-toolbar horisontal-separator-after">
		<div class="base-block clearfix">
			<div class="inner">
				<form class="show-prices column">
					<fieldset>
						<legend class="title">Show prices:</legend>

						<input id="incl-tax" type="radio" value="0" name="include_price" class="radio visibly-hidden">
						<label for="incl-tax" class="label">Incl. tax</label>

						<input id="ex-tax" type="radio" value="1" name="include_price" checked="checked" class="radio visibly-hidden">
						<label for="ex-tax" class="label">Ex. tax</label>
					</fieldset>
				</form>
				<div class="column">
					<a href="#" class="login-select" title="Login">Login</a>
				</div>
				<div class="column">
					<a href="#" class="language-select" title="Sweden"><span class="flag"></span></a>
				</div>
			</div>
		</div>
	</div>

	<div class="header-block header">
		<div class="inner base-block clearfix">
			<h1 class="logo" title="Site logo: Demostore">Demostore</h1>
			<div class="container">
				<nav class="menu">
					<a href="#" class="btn active menu-item" title="Home">Home</a>
					<a href="#" class="btn menu-item" title="Women">Women</a>
					<a href="#" class="btn menu-item" title="Men">Men</a>
					<a href="#" class="btn menu-item" title="Kids">Kids</a>
				</nav>
				<div class="inset-field">
					<span class="search-icon"></span>
					<input type="search" value="Search" class="text-field search">
					<!--
					I've used value instead of placeholder for inputs because
					placeholder does not seem to be stylable through CSS.
					-->
				</div>
				<div class="shopping-cart inset-field">
					<p class="text-content">You have 2 items in cart</p>
					<button class="btn checkout" title="Go to checkout">Go to checkout</button>
					<ul class="dropdown">
						<li class="dropdown-item">
							<img src="" width="60" height="60" class="image">
							<div class="details">
								<h4 class="title" title="Product: Lorem ipsum dolor">Lorem ipsum dolor</h4>
								<p class="price">99:-</p>
								<a href="#" class="read-more" title="Read more">Read more</a>
							</div>
							<a href="#" class="remove">x</a>
						</li>
						<li class="dropdown-item">
							<img src="" width="60" height="60" class="image">
							<div class="details">
								<h4 class="title" title="Product: Dolor sit amet">Dolor sit amet</h4>
								<p class="price">99:-</p>
								<a href="#" class="read-more" title="Read more">Read more</a>
							</div>
							<a href="#" class="remove" title="Remove">x</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</header>